---
- name: Copy the authorized keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob: "{{ secure_openssh_server_authorized_keys }}"

- block:
  - name: Harden the SSH service with a secure configuration
    lineinfile:
      dest: '/etc/ssh/sshd_config'
      state: present
      regexp: "{{ item.regexp }}"
      insertafter: "{{ item.insertafter }}"
      line: "{{ item.line }}"
      validate: /usr/sbin/sshd -t -f %s
      backup: true
    with_items:
      - regexp: '^PermitRootLogin '
        insertafter: '^#PermitRootLogin '
        line: 'PermitRootLogin no'
      - regexp: '^PasswordAuthentication '
        insertafter: '^#PasswordAuthentication '
        line: 'PasswordAuthentication no'

  - name: Restart the SSH service
    systemd:
      name: sshd
      state: restarted
      daemon_reload: true
  become: true
